### ISSUE TITLE
Prevent the algorithm from generating self-intersecting polygons

### ISSUE THREAD

**Issue by mourner** [mapbox/concaveman#1]
In some cases, the algorithm generates self-intersections. We should fix this and guarantee that the resulting concave hull is a simple polygon.

**Comment by mourner** [comment]
Fixed partially but not quite, full fix in progress — will have to index concave hull segments with rbush too, and check intersections against all segments.

**Comment by rhwang201** [comment]
@mourner any updates on a full fix for self-intersections?

**Comment by mourner** [comment]
@rhwang201 did a full fix in https://github.com/mapbox/concaveman/commit/b2f27df9c7cd6444ae8c62f9cefc087fcba745e5. Are you experiencing a failing case?

**Comment by rhwang201** [comment]
@mourner seeing self-intersections in a project that uses `concaveman` to generate polygons. https://github.com/urbica/galton uses https://github.com/stepankuzmin/node-isochrone, which uses v1.1.1 of concaveman.

Can reproduce by starting a local Galton server following the "Example" section in the README, and then examining the output of `curl http://localhost:4000 --get --data 'lng=-122.139935&lat=37.422744&intervals=15&bufferSize=50&cellWidth=0.5&concavity=3&resolution=20000`

**Comment by mourner** [comment]
Can you set up a self-contained test case (just concaveman, without any additional libraries and servers)?
