### ISSUE TITLE
feature request: 3D

### ISSUE THREAD

**Issue by trusktr** [mapbox/concaveman#12]
I'd like to generate a 3D concave hull of 3D points. I'm on a quest to make it happen. The Wikipedia article on [Alpha Shapes](https://en.wikipedia.org/wiki/Alpha_shape) links to a [3D version of Alpha Shapes written in R](https://cran.r-project.org/web/packages/alphashape3d/index.html).

**Comment by mourner** [comment]
Not going to pursue 3D in this little library so closing.
