### ISSUE TITLE
Is there a way to add a buffer to the concave?

### ISSUE THREAD

**Issue by jackdh** [mapbox/concaveman#14]
Hello Lovely People,

As seen in my amazing drawing below, does anyone have an idea of how I can achieve something like it?

![image](https://user-images.githubusercontent.com/1907451/57929894-738f7400-78ac-11e9-8618-030a3fd4a470.png)

**Comment by imposeren** [comment]
I don't think that it's possible to achieve better performance than doing "buffer" operation after the concave hull so you can simply use some other library to calculate "buffer":
https://shapely.readthedocs.io/en/stable/manual.html#object.buffer

**Comment by mourner** [comment]
Yep.
