### ISSUE TITLE
Does the library guarantee that the coords will be picked from the input points and not cloned?

### ISSUE THREAD

**Issue by ozomer** [mapbox/concaveman#15]
Hi,
From knowing the theoretical algorithm, I guess that the returned values are "picked" from the original array of points (each is a "Javascript Object" - an array of two floats). I don't see why a future implementation would want to clone these arrays.
Is this guaranteed to be the same way in the future? If so, please mention this in the README.
If not, will it be guaranteed that the floating-point values will be copied and not "calculated"? i.e. that the convex result will not have points that are "very close" to some of the original points, but not equal (due to floating-point errors).

Thanks

**Comment by mourner** [comment]
> the returned values are "picked" from the original array of points
> Is this guaranteed to be the same way in the future?

Yes.
