### ISSUE TITLE
Look at replacing robust-orientation with robust-predicates

### ISSUE THREAD

**Issue by rowanwins** [mapbox/concaveman#16]
We've had a few issues upstream in Turf because of robust-predicates causing an issue.
````
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'
````
See related issue in [robust-orientation](https://github.com/mikolalysenko/robust-orientation/issues/4)

Potentially robust-predicates could be used to replace it, however in swapping one for the other there were changes

![Screen_2020_05_14](https://user-images.githubusercontent.com/6735870/81874103-840e2380-95c0-11ea-96c0-0568985bbb7b.jpg)

![ZoomedIn](https://user-images.githubusercontent.com/6735870/81874108-87a1aa80-95c0-11ea-85d5-8f6d4843d50a.jpg)

So It's not quite a drop in replacement yet but I thought I'd flag it here and I'll also open an issue in robust-predicates

**Comment by mourner** [comment]
Likely an issue with how you use `robust-predicates` (see my comment there).

Replacing the dependency is a great idea, I completely forgot `concaveman` used `robust-orientation`! One thing to note here is that `monotone-convex-hull-2d` also depends on `robust-orientation`, so we would need to replace the convex hull dependency as well.

**Comment by mourner** [comment]
The convex hull code seems small enough to just inline here: https://en.wikibooks.org/wiki/Algorithm_Implementation/Geometry/Convex_hull/Monotone_chain#JavaScript
